<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">prepareConsumerApi</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNClN0cmluZyBkYXRh
ID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICJkYXRhIik7DQoNCkpzb25PYmplY3Qgb2Jq
ID0gSnNvblBhcnNlci5wYXJzZVN0cmluZyhkYXRhKS5nZXRBc0pzb25PYmplY3QoKTsNCg0KSnNv
bk9iamVjdCBoZWFkZXIgPSBvYmouZ2V0KCJoZWFkZXIiKS5nZXRBc0pzb25PYmplY3QoKTsNCkpz
b25FbGVtZW50IGJvZHkgPSBvYmouZ2V0KCJib2R5Iik7DQpKc29uT2JqZWN0IGZvb3RlciA9IG9i
ai5nZXQoImZvb3RlciIpLmdldEFzSnNvbk9iamVjdCgpOw0KDQpHc29uIGdzb24gPSBuZXcgR3Nv
bkJ1aWxkZXIoKS5zZXRQcmV0dHlQcmludGluZygpLmNyZWF0ZSgpOw0KDQpJRGF0YSByZXF1ZXN0
SGVhZGVycyA9IGpzb25PYmplY3RUb0lEYXRhKGhlYWRlcik7DQpTdHJpbmcgcmVxdWVzdEJvZHkg
PSBnc29uLnRvSnNvbihib2R5KTsNClN0cmluZyBxdWVyeVBhcmFtID0ganNvbk9iamVjdFRvUXVl
cnlQYXJhbShmb290ZXIpOw0KDQoNCklEYXRhVXRpbC5wdXQoY3Vyc29yLCAicmVxdWVzdEhlYWRl
cnMiLCByZXF1ZXN0SGVhZGVycyk7DQpJRGF0YVV0aWwucHV0KGN1cnNvciwgInJlcXVlc3RCb2R5
IiwgcmVxdWVzdEJvZHkpOw0KSURhdGFVdGlsLnB1dChjdXJzb3IsICJxdWVyeVBhcmFtIiwgcXVl
cnlQYXJhbSk7</value>
</Values>
